all:
  children:
    testing:
      hosts:
        test-server:
          ansible_host: "{{ test_server_ip }}"
          ansible_user: "{{ server_user }}"
          domain: alumap-test.escalopa.com
    production:
      hosts:
        prod-server:
          ansible_host: "{{ prod_server_ip }}"
          ansible_user: "{{ server_user }}"
          domain: alumap-prod.escalopa.com
  vars:
    ansible_python_interpreter: /usr/bin/python3
    deploy_dir: /home/deploy/iu-alumni
